# Generated by Django 6.0.7 on 2026-07-31 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_herobanner"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="wishlist",
                    name="variant",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to="myapp.productvariant",
                    ),
                ),
                migrations.AddField(
                    model_name="wishlist",
                    name="variant_size",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to="myapp.productvariantsize",
                    ),
                ),
                migrations.RemoveField(
                    model_name="wishlist",
                    name="product",
                ),
                migrations.AlterUniqueTogether(
                    name="wishlist",
                    unique_together={("user", "variant_size")},
                ),
            ],
        ),
    ]